#r "System.Xml.Linq" 
#r "../../../packages/FSharp.Data/lib/net40/FSharp.Data.dll" 
#r "../../../packages/Http.fs/lib/net40/HttpClient.dll" 
#r "../../../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll" 
#r "../../../packages/SwaggerProvider/lib/net45/SwaggerProvider.dll" 
#r "../../../packages/YamlDotNet/lib/net35/YamlDotNet.dll" 
#r "../../../packages/SwaggerProvider/lib/net45/SwaggerProvider.Runtime.dll" 
#r "../../../packages/SwaggerProvider/lib/net45/SwaggerProvider.DesignTime.dll" 
printfn "Loaded group Main" 